### ISSUE TITLE
Visual regression testing could be nice to have in future

### ISSUE THREAD

**Issue by johnrees** [theopensystemslab/planx-new#173]
I just ran into an issue where we fixed a visual bug in the editor but it created a new bug when there were more nodes on screen #172

To avoid needing to remember to check the various scenarios future, one option might be to run a visual diff on PRs with a service like https://percy.io

refs:

https://medium.com/loftbr/visual-regression-testing-eb74050f3366

**Comment by DafyddLlyr** [comment]
To be discussed with @ianjon3s at Strategy Days.
